### ISSUE TITLE
Feature Request: Lightmapped Liquid surfaces support

### ISSUE THREAD

**Issue by dumptruckDS** [andrei-drexler/quakespasm#10]
This issue over on vkQuake illustrates the request perfectly. Something to consider.
https://github.com/Novum/vkQuake/issues/413#issue-1092841390

**Comment by j4reporting** [comment]
wow. this was quick.  Which custom maps support this feature?

**Comment by andrei-drexler** [comment]
No idea, I just made a [test map](https://github.com/andrei-drexler/quakespasm/files/7815945/litwater.zip) myself...
