### ISSUE TITLE
[Bug] Water transparency not working

### ISSUE THREAD

**Issue by NightFright2k19** [andrei-drexler/quakespasm#12]
In latest build (v0.3.0), water transparency (_r_wateralpha_) does not seem to work when changing the CVAR value, same with other liquids (_r_lavaalpha_, _r_slimealpha_, _r_telealpha_). Apparently, it's the same with _r_novis_.

**Comment by j4reporting** [comment]
works for me (Windows x64 build) 
r_lavaalpha, r_slimealpha, r_telealpha all 0 
r_wateralpha  .x 
either r_novis 1  or  watervised map  or externel vis files installed in maps folder

DM5:
![spasm0000](https://user-images.githubusercontent.com/45177907/148952501-42139001-50ba-46be-8b3e-e69818dbf695.png)

**Comment by NightFright2k19** [comment]
OK, that's weird. I can't get it working, using pak0.pak from the Quake remaster (Kex) which has vispatched maps. Will attach my current config.cfg, maybe there's something I didn't set up right?
[config.txt](https://github.com/andrei-drexler/quakespasm/files/7847264/config.txt)
