### ISSUE TITLE
feature request: multiple gamedir support

### ISSUE THREAD

**Issue by neogeographica** [andrei-drexler/quakespasm#13]
For parity with vkQuake, Quakespasm-Spiked, FTE, DarkPlaces, and qbism Super 8. More long-winded justification available in the vkQuake issue I filed at https://github.com/Novum/vkQuake/issues/230 .

The resolution would likely just be a pull request from https://github.com/neogeographica/ironwail/tree/multigame , with change details in the commit comments there.

**Comment by andrei-drexler** [comment]
Support for multiple game dirs sounds like a sensible addition. I'm less convinced about the benefits of -basegame, but seeing you already have the code ready, I'll take it.

**Comment by neogeographica** [comment]
All righty. PR is up https://github.com/andrei-drexler/quakespasm/pull/22

**Comment by andrei-drexler** [comment]
Thanks! Merged in https://github.com/andrei-drexler/quakespasm/commit/7b40833b1bd900cd6c07d2d74ead04dace456141
