### ISSUE TITLE
[Bug] Wateralpha doesn't work on some maps

### ISSUE THREAD

**Issue by h4724** [andrei-drexler/quakespasm#15]
![udob2 in ironwail](https://user-images.githubusercontent.com/93443653/149220726-4676974b-60c7-4b41-b31b-661a3274b0c4.png)
vs Quakespasm:
![udob2 in QS](https://user-images.githubusercontent.com/93443653/149220736-9507cc19-11ec-4ebd-b536-7bc0a4c35d48.png)

Like I said, not all maps are the same, for some it just works. 
![udob1_4 in ironwail](https://user-images.githubusercontent.com/93443653/149218386-c66605bb-cf92-49d1-b004-ddba6fb38f11.png)

Here the pool in the middle is func_illusionary, while the surrounding ones are worldspawn water brushes, so the problem isn't with transparency on liquid textures in general.
![d1m7 in ironwail](https://user-images.githubusercontent.com/93443653/149221228-97ad6867-4229-4333-bde6-916ab611d843.png)

**Comment by andrei-drexler** [comment]
Thanks! Should be fixed in https://github.com/andrei-drexler/quakespasm/commit/b66f78c8c46804e080b32526985a9102ed45b42a
