### ISSUE TITLE
[Bug] r_shadows no longer has an effect

### ISSUE THREAD

**Issue by Immorpher** [andrei-drexler/quakespasm#16]
Although not perfect, I enjoyed the r_shadows option in Quakespasm, helped immerse the models a bit more into the levels. However it seems to no longer work.

A pipe dream would be a shadow system similar to KEX Quake. And the realtime lighting of FTEQW is pretty cool too! What can I say, I am a shadow addict haha.

**Comment by NightFright2k19** [comment]
I can confirm this. It doesn't matter if you set it to 1 or 2, no shadows are shown at all.

**Comment by andrei-drexler** [comment]
I didn't really like the hacky look of those shadows, so they're not implemented at all. I guess I forgot to remove the cvar. "Fixed" in https://github.com/andrei-drexler/quakespasm/commit/9e039368228c4ae06f52f54334d919f20fc51f5a.
