### ISSUE TITLE
[Bug] r_showbboxes doesn't work

### ISSUE THREAD

**Issue by bstordeur** [andrei-drexler/quakespasm#17]
For some reason, r_showbboxes 1 doesn't work in this engine, it doesn't display anything, while it does in QS/QSS/vkQ (for vkQ it was fixed fairly recently).

**Comment by andrei-drexler** [comment]
It's just not implemented currently - never got around to it.

**Comment by andrei-drexler** [comment]
Fixed in https://github.com/andrei-drexler/quakespasm/commit/b411af4c6fff220cb9dd26bab3ee2a6d7d008f40
