### ISSUE TITLE
Hitching

### ISSUE THREAD

**Issue by Dreded** [andrei-drexler/quakespasm#25]
~~at 250fps I seem to be getting a lot of weird stutters, easiest to notice when dropping, so ramps and especially elevators. If I try to move in the E1M1 elevator its like im doing little bunny hop stutters.~~

wrote that then realized to be helpful I should try and install the original quakespasm and it has the same issue, read up on it a bit and found out its due to physics issues, which is exactly what this is supposed to be fixing(according to the readme)

Tried changing max_hostfps to 72 and that fixed the issue, then changed it back to 250 and the issue was also gone.

Restarted the game(exited) and issue returned until doing max_hostfps 72 then max_hostfps 250

So its not decoupling the physics unless the max_hostfps command is used.

**Comment by andrei-drexler** [comment]
Thanks, the extra info was very helpful! Fixed in https://github.com/andrei-drexler/quakespasm/commit/24e50f804d5d27b5f117b46ee63597fecb9115cb
