### ISSUE TITLE
UHD 620:  GL_DynamicsBuffersBeginFrame: sync failed  ( 0x04911B)  after loading a map

### ISSUE THREAD

**Issue by j4reporting** [andrei-drexler/quakespasm#8]
I tried to run the gl-test2 binary  on a UHD 620 iGPU,   bindless_texture  is supported, but it will bail out with the above error.  Current git version fails with the same error.  

win10 Enterprise (20H2) 
Driver  27.20.100.8681     I think I'll not be able to upgrade the GFX Driver. This system has some enterprise 'snake oil' programms running, but vanilla quakespasm and vkquake have no issues.

**Comment by andrei-drexler** [comment]
Thanks for the report! There was a typo in the error message, so the actual code is 0x911B, which means the GPU took more than 2 seconds to finish rendering a previous frame. This should be fixed in the latest code.

**Comment by j4reporting** [comment]
with commit 350895e91af4e29b571f129e7e3eda36ab26cb4e   I can load  maps, but the console will freeze and never switch to the world view.  Game is running, I can hear ambiant sound, or jump sounds. typing 'disconnect' will not recover the console.

with latest commit c0bd86797d2a06bd8b65edf3a1dc02ee710f5bb0  I get a new error message and process  aborts.  

![qspasmgl4_error](https://user-images.githubusercontent.com/45177907/146964183-d1d3ba80-7623-4ec0-b4ca-19e2812e57d0.png)


both versions work when started with the option  -nobindless

**Comment by andrei-drexler** [comment]
Pushed c82824ae0ce3b7734e3990c6380444c71dd6a3b4 which *might* fix the shader compilation error.

**Comment by j4reporting** [comment]
It aborts at startup  with same error message as the previous  version.

**Comment by andrei-drexler** [comment]
It was worth a try, I guess, thanks for testing it so quickly. I might end up disabling the bindless codepath on Intel for now, it's hard to figure out what the issue is by just taking random shots in the dark.

**Comment by andrei-drexler** [comment]
Pushed a few more commits - ae22e1dadce5d639477284db6b3e7e948091a8af in particular should fix the compilation error.

**Comment by j4reporting** [comment]
I can confirm that latest git version fixed this issue.  Is the Intel driver stricter or just less capable than the AMD or NVIDIA drivers?

**Comment by andrei-drexler** [comment]
> I can confirm that latest git version fixed this issue.

Oh, that's such a relief, thanks again for your help!

> Is the Intel driver stricter or just less capable than the AMD or NVIDIA drivers?

I think the shader compilation error is a bug in the Intel driver, unless I missed some subtle detail in the bindless spec that AMD/NV don't care about. The black screen bug after loading a map - I'm still not entirely sure what was causing it, I tried a few different things based on some hunches, but we'd have to go through the commits to find out which one fixed it.

**Comment by j4reporting** [comment]
> I'm still not entirely sure what was causing it, I tried a few different things based on some hunches, but we'd have to go through the commits to find out which one fixed it.

I had no time yet to check the individual commits. 

This may be another Intel driver issue.  But commit  1992a0200bc29890243e33f01785c03f21c86efe does not work well on Intel GPUs. No textures are visible on walls when r_softemu 0  is configured (win32  binary).  A x64 binary will crash w/o any error message.  Both binaries compiled with msys2.  

![qspasm_softemu_0](https://user-images.githubusercontent.com/45177907/147563784-91f8aecc-ab25-4001-9063-43d7e3445c15.png)

**Comment by j4reporting** [comment]
this is only reproducible  with binaries compiled  with msys2.   VS2019  binaries are fine.

**Comment by andrei-drexler** [comment]
Great, thanks for letting me know, I was just about to zip up some VS2022 binaries to rule that one out! I wasn't actually expecting msys to be the problem, though, so I was also going to suggest running with `-gldebug` and then `-nobufferstorage`/`-nomultibind` to see if we can narrow down the issue, but I guess that's no longer necessary. Thanks again for all the testing!

~~The only Intel GPU I have on hand is an old Atom x7 8700 (Gen 8 graphics, I think, so one generation older than the 540), but I can't reproduce this issue there with either x86 or x64 binaries (compiled with Visual Studio Community 2022). Could you try running the exe with `-gldebug` to see if there are any GL errors in the console? There might be a couple of 'shader recompiled due to state change' warnings, those are benign. If there aren't any errors, testing with `-nobufferstorage` or `-nomultibind` could also help narrow down the issue.~~

**Comment by j4reporting** [comment]
here is the gldebug output.
started binary configured  with r_softemu 1      no error
changed t_softemu to 0  in console  and tons of  these lines were logged. 

```
using shaders, 13, "postprocess|PALETTIZE 1", 14, "postprocess|PALETTIZE 1"
GL api error [#1282/high]: Error has been generated. GL error GL_INVALID_OPERATION in (null): (ID: 3588625117) GL
error GL_INVALID_OPERATION: mismatched type setting uniform of location "0" in program 15, "postprocess|PALETTIZE 1"
using shaders, 13, "postprocess|PALETTIZE 1", 14, "postprocess|PALETTIZE 1"

```

**Comment by andrei-drexler** [comment]
Thanks, should be fixed in https://github.com/andrei-drexler/quakespasm/commit/357533de6e761dcdec04927cd9e0e883e4d01693

**Comment by j4reporting** [comment]
Sorry, I forgot to give feedback. Yes this solved the problem. 

But unfortunately a later commit broke the support for external vis files.  Client crashes with no error message.  I was wondering why the AD maps loaded, but not the original ID maps.

**Comment by andrei-drexler** [comment]
Oh, good catch, I don't use external vis files so I missed that. Fixed in https://github.com/andrei-drexler/quakespasm/commit/e96a839aba0bbb158758464a93b54026a5af2cd3. Thanks again!

**Comment by j4reporting** [comment]
Confirmed. Thanks!

**Comment by andrei-drexler** [comment]
Thank *you* for all your help, not just the testing, but the extra info. For the last issue, for example, knowing that it was related to external vis files meant that I was able to download a vis patch, reproduce the issue, fix it and test the fix in just a few minutes. Figuring out that crucial detail alone would have taken me longer than that. So, thanks again!

**Comment by j4reporting** [comment]
Happy to help.  I know from experiance how much any  detailed and precise bug reports help to narrow down issues, not just in coding.
fun fact:  playdemo  / timedemo  was still working.  I'd guess playdemo does not load any external vis file.
